<?php
return array(
  'keyfobs_aws_access_key_id' => array(
    'group_name' => 'Keyfob AWS Settings',
    'group' => 'keyfobs',
    'title' => 'AWS Access Key ID',
    'name' => 'keyfobs_aws_access_key_id',
    'description' => 'AWS Access Key ID',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'add' => '5.19',
    'html_type' => 'text',
    'settings_pages' => ['keyfobs' => ['weight' => 10]],
  ),

  'keyfobs_aws_secret_access_key' => array(
    'group_name' => 'Keyfob AWS Settings',
    'group' => 'keyfobs',
    'title' => 'AWS Secret Access Key',
    'name' => 'keyfobs_aws_secret_access_key',
    'description' => 'AWS Secret Access Key',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'add' => '5.19',
    'html_type' => 'text',
    'settings_pages' => ['keyfobs' => ['weight' => 20]],
  ),

  'keyfobs_aws_region' => array(
    'group_name' => 'Keyfob AWS Settings',
    'group' => 'keyfobs',
    'name' => 'keyfobs_aws_region',
    'title' => 'AWS Region',
    'description' => 'AWS Region',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'add' => '5.19',
    'html_type' => 'text',
    'settings_pages' => ['keyfobs' => ['weight' => 30]],
  ),

  'keyfobs_aws_sqs_queue_url' => array(
    'group_name' => 'Keyfob AWS Settings',
    'group' => 'keyfobs',
    'name' => 'keyfobs_aws_sqs_queue_url',
    'title' => 'SQS Queue Name',
    'description' => 'SQS Queue URL',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'add' => '5.19',
    'html_type' => 'text',
    'settings_pages' => ['keyfobs' => ['weight' => 40]],
  ),
);

// return array(
//   'multisite_acl_enabled' => array(
//     'group_name' => 'Multi Site Preferences',
//     'group' => 'multisite',
//     'name' => 'multisite_acl_enabled',
//     'type' => 'Boolean',
//     'default' => 1,
//     'add' => '4.3',
//     'is_domain' => 1,
//     'is_contact' => 0,
//     'description' => 'Multisite ACL is enabled',
//     'help_text' => 'Should multisite based ACLs be enabled for this site',
//   ),
//   'multisite_custom_tabs_restricted' => array(
//     'group_name' => 'Multi Site Preferences',
//     'group' => 'multisite',
//     'name' => 'multisite_custom_tabs_restricted',
//     'type' => 'Boolean',
//     'default' => 0,
//     'add' => '4.3',
//     'is_domain' => 1,
//     'is_contact' => 0,
//     'description' => 'Limit custom tabs visible on this site',
//     'help_text' => 'Should multisite based ACLs be enabled for this site',
//   ),
//   'multisite_custom_tabs_enabled' => array(
//     'group_name' => 'Multi Site Preferences',
//     'group' => 'multisite',
//     'name' => 'multisite_custom_tabs_enabled',
//     'type' => 'Array',
//     'default' => NULL,
//     'add' => '4.3',
//     'is_domain' => 1,
//     'is_contact' => 0,
//     'description' => 'Array of tabs which should be visible on this site',
//     'help_text' => 'Enabled Custom Tabs',
//   ),
//  );
