<div class="form-item">
  <fieldset><legend>{ts}Keyfob Information{/ts}</legend>
    <div class="crm-block crm-form-block crm-cividesk-apikey-form-block">
      <div class="label" style="float:left">Code:&nbsp;</div>
      <div style="float:left"><strong>{$keyfob->code}</strong></div><br />

      <div class="label" style="float:left">Access Level:&nbsp;</div>
      <div style="float:left"><strong>{$keyfob->access_level}</strong></div><br />

      <div class="action-link">
          <a class="button" href="{$keyfobFormUrl}" accesskey="N"><span><div class="icon add-icon"></div>{if $keyfob->id}Edit{else}Add{/if} Keyfob</span></a>
      </div>
    </div>
  </fieldset>
</div>

<!-- <h3>This new page is generated by CRM/Keyfobs/Page/Keyfob.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$keyfobCode}</p>
{* Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>
-->
